version: '3.0'
services:
  web:
    build: .
    volumes:
      - ./models/:/app/models
    ports:
      - "5005:5005"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - ACTION_ENDPOINT=http://localhost:8080/webhook
      - MAILCHIMP_API_KEY=<YOUR_API_KEY>
      - MAILCHIMP_USER=<YOUR_USER>
      - MAILCHIMP_LIST_ID=<YOUR_LIST_ID>
    restart: always
